stages:
- build
- github_pr
- security
- approval
- deploy

build:
    stage: build
    image: mcr.microsoft.com/dotnet/sdk:8.0

    script:
    - cd app/SampleWebApi
    - dotnet restore
    - dotnet build

    rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

create_github_pr:
  stage: github_pr

  image:
    name: mcr.microsoft.com/powershell:latest

  before_script:
    - mkdir -p reports

  script:
    - pwsh scripts/create-github-pr.ps1
  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  artifacts:
    paths:
      - reports/

github_security_gate:
    stage: security
    image: mcr.microsoft.com/powershell:latest

    script:
    - pwsh scripts/wait-for-codeql.ps1
    - pwsh scripts/wait-for-dependency-review.ps1
    - pwsh scripts/github-security-check.ps1

    rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    artifacts:
        when: always
        expire_in: 30 days
        paths:
            - reports/

    allow_failure: false


manual_approval:
    stage: approval
    when: manual

    script:
    - echo "CAB Approval Granted"

    rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:
    stage: deploy

    script:
    - echo "Deploying Application"

    rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
